### ISSUE TITLE
Bug: scrolling through the note resets cursor to the first line

### ISSUE THREAD

**Issue by mintydev789** [maltaisn/another-notes-app#105]
Whenever you scroll through a long note the cursor gets reset to the very top of the note.

Steps to reproduce:

1. Create a note long enough that it requires scrolling.
2. Set the cursor to any desired position in the note.
3. Scroll the note up or down. The cursor should now be reset to the very start of the note.
4. Type something. The text should be input at the very beginning, not where the cursor was intended to be.

Expected behavior: scrolling the screen does not change the cursor's position.

**Comment by dd-dreams** [comment]
Can't reproduce.

**Comment by dmint789** [comment]
I guess it must be phone-dependent then. I'm on Pixel 6.

**Comment by dd-dreams** [comment]
Try reinstalling the app maybe?

**Comment by maltaisn** [comment]
No it won't fix it... it's most probably a bug.

**Comment by dmint789** [comment]
> Try reinstalling the app maybe?

Hmm, that actually seems to have worked. It's probably been fixed in one of the updates since I created this issue.

**Comment by dmint789** [comment]
@maltaisn oh, I didn't see your comment in time. Feel free to reopen if need be.

**Comment by dd-dreams** [comment]
:D

**Comment by mintydev789** [comment]
The bug is still present. @maltaisn could you please reopen the issue?

**Comment by mintydev789** [comment]
Oh, I just realized I didn't have the latest version. I believe it works now, thanks!
