### ISSUE TITLE
Navigation Bar Cuts Off Status Bar In Landscape Mode

### ISSUE THREAD

**Issue by ghost** [maltaisn/another-notes-app#56]
Great app. However, I recently noticed that the status bar is cut off by the navigation bar in landscape mode on your app.

**Comment by maltaisn** [comment]
Can you provide more details? Device, android version, a screenshots?

**Comment by GithubContributor832** [comment]
The notes automatically deleted after moving to recycle bin are notes created over 7 days old. It doesn't seem to use time of item move and delete seven days after that.

**Comment by maltaisn** [comment]
You're right, moving an item used to change the last modified date, but I changed that some time ago not thinking about the recycle bin delay. I'll fix it.

**Comment by GithubContributor832** [comment]
I would like to say one note over a 7 day creation date did not automatically delete in recycle bin. Really strange.

**Comment by maltaisn** [comment]
I fixed the recycle bin bug, but I can't reproduce the issue with the status bar. I tried on a galaxy S8 and it's not occurring, so this is gonna be hard to fix for me. I'll leave this open in case you can identify the bug more closely, but I won't look at it for now.

**Comment by GithubContributor832** [comment]
What ROM were you on? I use efoundation custom ROM I flashed. Maybe it's the ROM and code not meshing well with it. I've had problems with Brave on this ROM until they fixed it with no problems on proprietary ROM. Just an idea not dumb in tech but far from savy. Thank you.

**Comment by maltaisn** [comment]
The Samsung ROM. Brave is open source I think, if you can link me to the issue you opened (?) it might help.

**Comment by GithubContributor832** [comment]
I know Brave is open source. However, it was a different problem with Brave that's now fixed. I don't know how it would help fix this problem. It's a closed issues on my account if you fish through.

**Comment by nhoeher** [comment]
The bug with the cut off toolbar in landscape mode still exists in the newest version of the app and I am able to consistently reproduce it in the emulator all the way from API 21 to API 33. I am already working on a fix and will create a PR soon.

## Steps to reproduce:
1. Use traditional three button navigation.
2. Change device orientation to landscape mode.

![image](https://user-images.githubusercontent.com/39745929/212546720-c5b50720-cbb8-483b-a4ed-96922d2cdf31.png)
![image](https://user-images.githubusercontent.com/39745929/212546741-f9f2ed2f-98d6-4327-b6a2-94c7e80f2ed5.png)
